### ISSUE TITLE
modify example p38

### ISSUE THREAD

**Issue by lesidaner** [ivoa-std/VOTable#56]
on Link tag in the example

LINK type="location"  href="http://ivoa.spectr/server?obsno="

but Link has no tribute type, should be content-role

Regards
Pierre

**Comment by tomdonaldson** [comment]
It is recognized that Appendix A has a number of problems with its examples.  The current plan (see #53) is to replace appendix A with an independent implementation note in version 1.6.

Since Appendix A begins with 

> The definitions enclosed in this appendix are not part of VOTable 1.1, but are considered as candidates for VOTable improvements.

perhaps no additional cautions are needed now for readers of this section.

**Comment by tomdonaldson** [comment]
In looking more closely at this issue, I agree that `LINK` should not have an attribute `type`, but I'm less sure what makes this correct.  From the descriptive text above it looks like the `type="location"` was supposed to be on the `FIELD`, but even that is explicitly not part of VOTable 1.5, just reserved for possible future use. I'm not sure if moving it there matches the original intent.

I would be happy to consider PRs to address this, but don't think it is worth much effort or discussion since the whole appendix is non-normative and slated for deletion.

**Comment by tomdonaldson** [comment]
This was addressed with PR #62
